import type { Metadata } from "next";
import { Montserrat, Roboto } from "next/font/google";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import { Theme, ThemePanel } from "@radix-ui/themes";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} flex flex-col`}>
        <Theme accentColor="blue" radius="large" appearance="dark">
          <ThemePanel defaultOpen={false} />
          {children}
        </Theme>
      </body>
    </html>
  );
}
